####################
# ORENETA Makefile #
# Abel Navarro     #
# March 2003       #
####################

### Main target ###
all: oreneta

### Targets ###

oreneta: Oreneta.java
	javac Oreneta.java

### Clean ###
clean:
	rm -Rf *.class

